### ISSUE TITLE
[Extension Host] Error: Language client is not ready yet

### ISSUE THREAD

**Issue by radustoenescu** [alanz/lsp#104]
I have a running `hie` server on my Ubuntu system.

I tried using VSCode with the following extension settings:

`{
    "languageServerHaskell.useHieWrapper": true,
    "languageServerHaskell.enableHIE": true,
    "languageServerHaskell.hlintOn": true,
    "languageServerHaskell.maxNumberOfProblems": 100
}`

No feature works when opening a Haskell file. When I try the `showType` command, for instance, I get:
`[Extension Host] Error: Language client is not ready yet` in the developer tools console.

**Comment by Bubba** [comment]
Does `$TMPDIR/hie.log` contain anything, or are you seeing 'Haskell HIE (project)" in the output dropdown?

**Comment by jneira** [comment]
@radustoenescu do you continue experiencing the issue? In that case imo this should be moved to [the haskell-ide-engine repo](https://github.com/haskell/haskell-ide-engine/issues/new).
