### ISSUE TITLE
Consider moving some helper functions from haskell-ide-engine into haskell-lsp-types

### ISSUE THREAD

**Issue by bubba** [alanz/lsp#151]
It would make sense to make them available for other users. See https://github.com/haskell/haskell-ide-engine/pull/1170/files/fe8ed0c349ca4eb77d450086bf3a3c166c407b0f#discussion_r277166217

**Comment by alanz** [comment]
And we once again discover that rebase sucks. The prior link is dead.

I have moved 
 - rangeLinesFromVfs
 - PosPrefixInfo(..)
 - getCompletionPrefix

over in https://github.com/alanz/haskell-lsp/pull/164

**Comment by jneira** [comment]
Some work was done, @bubba, are there more functions to move (taking in account that now we are deprecating hie)? In that case a list or any general consideration would be useful

**Comment by wz1000** [comment]
I think this is no longer relevant.
