### ISSUE TITLE
Move Language.Haskell.LSP.Messages into haskell-lsp-types

### ISSUE THREAD

**Issue by bubba** [alanz/lsp#159]

**Comment by bubba** [comment]
@alanz after thinking about this for a bit, I think the reason why it was not originally moved into haskell-lsp-types might have been that the wrapper types inside Language.Haskell.LSP.Messages aren't strictly a part of the LSP specification. They're types used only by haskell-lsp. Does it then make sense to leave them as a part of haskell-lsp? Or is it ok/used widely enough to consider moving into haskell-lsp-types?

**Comment by alanz** [comment]
Well, one argument is that the messages *are* part of the types.

My primary motivation for splitting them was to put all the TH stuff in a separate package that changed rarely, so working on `haskell-lsp` was not so achingly slow.

So using that criterion it should probably be called `haskell-lsp-th-types`, and we should try to limit them to that.

**Comment by wz1000** [comment]
Invalidated by #244
