### ISSUE TITLE
InitializeParams is missing _workDoneToken

### ISSUE THREAD

**Issue by adamwalker** [alanz/lsp#255]
See here: https://github.com/microsoft/language-server-protocol/issues/904

Adding this field and making it available to the onStartup function would allow language servers to report on progress during initialization. This is useful if you have lots of parsing/typechecking to do before you can respond to any requests. 

I've hacked together a version that does this here: https://github.com/adamwalker/haskell-lsp/commit/300ab53625b591e3e74d225bad1301bb00fdaab8

But, I didn't make a PR, since I changed the type of onStartup, which would break a lot of code for users of this library.

**Comment by wz1000** [comment]
Fixed in #244
