### ISSUE TITLE
_isPreferred defined twice in CodeAction

### ISSUE THREAD

**Issue by felixonmars** [alanz/lsp#272]
https://github.com/alanz/lsp/commit/9f2415c58f45982edc4b2f84fa9b5c2c6cd191da added _isPreferred once again while it's already present. So now `_isPreferred :: Maybe Bool,` is defined twice, even the comments are the same.

**Comment by wz1000** [comment]
Fixed in https://github.com/alanz/lsp/commit/4ac98f0fead03ca9e597328b6a9942204cb1a6f1
