### ISSUE TITLE
No handler for workspace symbol method

### ISSUE THREAD

**Issue by rumblesan** [alanz/lsp#64]
Hi, I've just started setting up and using the haskell-ide-engine today with neovim and the [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) plugin

Most things seem to be working ok, but when I try to use the workspace symbols functionality I'm having vim crash and seeing the below error

`[Error] haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("query",String "")])),("method",String "workspace/symbol"),("id",Number 2.0)])`

I've found the [relevant line](https://github.com/alanz/haskell-lsp/blob/master/src/Language/Haskell/LSP/Core.hs#L273) in this lib so thought here would be the right place to raise a bug. I can see that a handler is defined for the workspace/symbol method and have no idea what the issue might be.

I'm building the ide engine from source using [the most recent commit](https://github.com/haskell/haskell-ide-engine/commit/358c6489eb1724b5d29698fe28fc389c12cdc10f)

Any help much appreciated

**Comment by jneira** [comment]
Lot of time since this, @rumblesan, do you continue experiencing this issue?

**Comment by rumblesan** [comment]
Hey, sorry for the slow response. I've not been writing much haskell recently and so only just got around to checking.

I do appear to still be seeing this issue.
ran `:call FindWorkspaceSymbol()`
error is slightly different from what I was seeing but basically the same
`Symbol Search: ImprovizEnv[LC] [Error] haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("query",String "Imp
rovizEnv")])),("method",String "workspace/symbol"),("id",Number 3.0)])`

this is with the currently most up to date versions of LanguageClient-neovim and current master for the haskell ide engine

**Comment by rumblesan** [comment]
haskell-ide-engine from commit b7fd5fb04b1711d433fc203751bc61624edc8dd0  built new and being run through `hie-wrapper`

**Comment by wz1000** [comment]
This is a bug in the server, not the lsp library
