### ISSUE TITLE
Stub URL in error messages

### ISSUE THREAD

**Issue by nponeccop** [alanz/lsp#69]
https://github.com/alanz/haskell-lsp/blob/98f7cd260a37c6903a78059901b64149751fb222/src/Language/Haskell/LSP/Core.hs#L396-L398

contains an invalid url https://marketplace.visualstudio.com/items?itemName=xxxxxxxxxxxxxxx

Ideally `haskell-lsp` should not contain any references to `haskell-ide-engine` or vsCode integration

**Comment by wz1000** [comment]
Fixed in #244
